/**
 * PDF Export Utilities
 * Exports solutions to formatted PDF files
 */

interface ExportOptions {
  includeSteps: boolean;
  includeTimestamp: boolean;
  title?: string;
}

/**
 * Export solution to PDF
 * Uses jsPDF library (should be added to package.json)
 */
export async function exportSolutionToPDF(
  problem: string,
  result: string,
  category: string,
  steps: Array<{ description: string; expression: string }>,
  options: ExportOptions = {
    includeSteps: true,
    includeTimestamp: true,
  }
) {
  try {
    // Dynamic import to keep bundle small
    const { default: jsPDF } = await import('jspdf');

    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    let yOffset = 20;
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;

    // Header
    doc.setFontSize(20);
    doc.setTextColor(79, 39, 245); // Indigo
    doc.text('MathSolver Solution', margin, yOffset);

    yOffset += 15;

    // Problem Details
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Problem: ${problem}`, margin, yOffset);
    yOffset += 8;

    doc.setTextColor(34, 197, 94); // Green for result
    doc.setFontSize(14);
    doc.text(`Answer: ${result}`, margin, yOffset);
    yOffset += 10;

    // Category
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Category: ${category}`, margin, yOffset);
    yOffset += 8;

    if (options.includeTimestamp) {
      doc.text(`Date: ${new Date().toLocaleString()}`, margin, yOffset);
      yOffset += 10;
    }

    // Steps
    if (options.includeSteps && steps.length > 0) {
      yOffset += 5;
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      doc.text('Step-by-Step Solution:', margin, yOffset);
      yOffset += 8;

      doc.setFontSize(10);
      steps.forEach((step, index) => {
        // Check if new page needed
        if (yOffset > pageHeight - 20) {
          doc.addPage();
          yOffset = 20;
        }

        // Step number
        doc.setTextColor(79, 39, 245);
        doc.text(`Step ${index + 1}:`, margin, yOffset);
        yOffset += 6;

        // Description
        doc.setTextColor(0, 0, 0);
        const descLines = doc.splitTextToSize(step.description, 180);
        doc.text(descLines, margin + 5, yOffset);
        yOffset += descLines.length * 4 + 2;

        // Expression
        doc.setTextColor(100, 100, 100);
        doc.setFont(undefined, 'italic');
        const exprLines = doc.splitTextToSize(step.expression, 170);
        doc.text(exprLines, margin + 10, yOffset);
        doc.setFont(undefined, 'normal');
        yOffset += exprLines.length * 4 + 6;
      });
    }

    // Footer
    yOffset = pageHeight - 10;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by MathSolver 🧮', margin, yOffset);

    // Save
    const filename = `MathSolver_${problem.slice(0, 20).replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
    doc.save(filename);
  } catch (error) {
    console.error('Failed to export PDF:', error);
    throw new Error('PDF export failed. jsPDF might not be installed.');
  }
}

/**
 * Export multiple solutions to single PDF
 */
export async function exportHistoryToPDF(
  solutions: Array<{
    problem: string;
    result: string;
    category: string;
    steps: Array<{ description: string; expression: string }>;
    timestamp?: number;
  }>
) {
  try {
    const { default: jsPDF } = await import('jspdf');

    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    let yOffset = 20;
    const pageHeight = doc.internal.pageSize.getHeight();

    // Title page
    doc.setFontSize(24);
    doc.setTextColor(79, 39, 245);
    doc.text('MathSolver History Report', 15, yOffset);

    yOffset += 20;
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 15, yOffset);
    doc.text(`Total Problems: ${solutions.length}`, 15, yOffset + 8);

    yOffset += 20;

    solutions.forEach((sol, idx) => {
      if (yOffset > pageHeight - 30) {
        doc.addPage();
        yOffset = 20;
      }

      doc.setFontSize(12);
      doc.setTextColor(79, 39, 245);
      doc.text(`Problem ${idx + 1}:`, 15, yOffset);
      yOffset += 8;

      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      doc.text(`Q: ${sol.problem}`, 20, yOffset);
      yOffset += 6;

      doc.setTextColor(34, 197, 94);
      doc.text(`A: ${sol.result}`, 20, yOffset);
      yOffset += 6;

      doc.setTextColor(100, 100, 100);
      doc.text(`Category: ${sol.category}`, 20, yOffset);
      yOffset += 10;
    });

    doc.save(`MathSolver_History_${new Date().toISOString().split('T')[0]}.pdf`);
  } catch (error) {
    console.error('Failed to export history:', error);
    throw new Error('History export failed.');
  }
}
